version: '3'

services:
  project:
    build: .
    container_name: barkan
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - 8002:8000

  redis:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
