# Generated by Django 4.1.6 on 2023-05-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barkan', '0002_remove_history_service_guide_experience_history_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='direct_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='customer',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='barkan.customer'),
        ),
        migrations.AddField(
            model_name='service',
            name='date_publish',
            field=models.DateField(null=True),
        ),
    ]
